#!/usr/bin/env python3
"""Audit harness md-files for token budget violations. Stdlib only.

Usage: python3 audit.py [repo_root]
Exit 0 = clean, 1 = violations found.

Dual-harness aware: this repo tracks both Claude Code (.claude/) and Codex
(.agents/, .codex/) equally.
Skills/rules are matched by filename/path pattern, not a single CLI's
directory.
Skill content lives under .agents/skills/<name>/SKILL.md, the one real
copy; .claude/skills is a directory-level symlink to it, so os.walk()
(followlinks=False) never descends into .claude/skills and each SKILL.md
is only ever reached via the .agents/skills/ path.
The realpath dedup below stays in place for other symlink cases (e.g.
.codex/ config), even though it's no longer load-bearing for skills
specifically.
Subagents stay .claude-only - Codex has no Task-tool/subagent
equivalent, so there's no .codex/agents to scan.
"""
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from budgets import BUDGETS  # noqa: E402

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."

STRIP_COMMENTS = re.compile(r"<!--.*?-->", re.DOTALL)
VOLATILE_PATTERN = re.compile(
    r"\b(20\d\d-\d\d-\d\d|sprint\s*[#\w-]*\d|current (branch|sprint|version|status)|as of|updated on)\b",
    re.IGNORECASE,
)
REF_PATTERN = re.compile(r"(?:\]\(|`|\s)((?:agent_docs|thoughts|references|scripts|\.claude|\.agents)/[\w./-]+\.(?:md|py|sql|json))")
MULTI_SENTENCE_PATTERN = re.compile(r"[a-z0-9`)\]]\. [A-Z]")


def multi_sentence_lines(text: str):
    """Heuristic for md-format's one-sentence-per-line rule: a prose line
    containing '. X' mid-line is probably two sentences hard-wrapped
    together. Skips frontmatter, code fences, list/table/blockquote lines
    (blockquotes may be deliberate before/after examples of bad style)."""
    in_fm = False
    in_code = False
    hits = []
    for i, line in enumerate(text.splitlines(), 1):
        if line.strip() == "---":
            in_fm = not in_fm
            continue
        if in_fm:
            continue
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        s = line.strip()
        if not s or s.startswith(("-", "*", "|", ">", "#")) or re.match(r"^\d+\.\s", s):
            continue
        if MULTI_SENTENCE_PATTERN.search(s):
            hits.append((i, s[:80]))
    return hits


def tokens(text: str) -> int:
    return len(STRIP_COMMENTS.sub("", text).encode("utf-8")) // 4


def description_words(text: str) -> int:
    m = re.search(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return 0
    d = re.search(r"description:\s*(?:>\s*\n)?((?:.|\n)*?)(?=\n\w+:|\Z)", m.group(1))
    return len(d.group(1).split()) if d else 0


def collect():
    files = {}
    seen_real = set()
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in {".git", "node_modules", "vendor", ".venv"}]
        for fn in filenames:
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, ROOT)
            if fn in ("CLAUDE.md", "AGENTS.md"):
                kind = "root_md" if os.path.dirname(rel) in ("", ".") else "nested_md"
            elif rel.startswith(os.path.join(".claude", "rules")) and fn.endswith(".md"):
                kind = "rule"
            elif fn == "SKILL.md":
                # Matched by filename, not a single CLI's directory.
                # The real copy lives under .agents/skills/x/SKILL.md;
                # .claude/skills is a directory-level symlink to it, so
                # followlinks=False keeps os.walk() from ever descending
                # into .claude/skills.
                kind = "skill"
            elif fn.endswith(".md") and rel.startswith(os.path.join(".claude", "agents")):
                kind = "agent"
            elif fn.endswith(".md") and rel.startswith("agent_docs" + os.sep) and fn != "harness-index.md":
                # Hand-authored deep-dive docs (architecture.md, incidents.md) -
                # no token budget (not always-loaded), but still checked for
                # dead references and duplicate rules. harness-index.md is
                # excluded: it's GENERATED by scripts/sync_harness.py, never
                # hand-edited, and would churn on every frontmatter change.
                kind = "deep_dive"
            elif fn == "harness-index.md":
                # GENERATED by scripts/sync_harness.py, never hand-edited -
                # excluded from every check, same as its agent_docs/ case above.
                continue
            elif fn.endswith(".md"):
                # Any other markdown file in the repo: README.md, todo/*.md,
                # service-level docs, etc.
                # No token budget.
                # Still checked for md-format one-sentence-per-line and dead
                # references.
                kind = "other_md"
            else:
                continue
            real = os.path.realpath(path)
            if real in seen_real:
                continue
            seen_real.add(real)
            with open(path, encoding="utf-8", errors="replace") as f:
                files[rel] = (kind, f.read())
    return files


def main():
    files = collect()
    if not files:
        print("no harness files found under", ROOT)
        return 0

    violations = []
    line_index = defaultdict(list)

    print(f"{'file':<55} {'kind':<10} {'tokens':>7} {'lines':>6}")
    for rel, (kind, text) in sorted(files.items()):
        tok = tokens(text)
        nlines = text.count("\n") + 1
        print(f"{rel:<55} {kind:<10} {tok:>7} {nlines:>6}")

        if kind in ("root_md", "nested_md", "rule") and tok > BUDGETS[kind]:
            violations.append(f"{rel}: {tok} tokens > budget {BUDGETS[kind]}")
        if kind == "skill" and nlines > BUDGETS["skill_lines"]:
            violations.append(f"{rel}: {nlines} lines > budget {BUDGETS['skill_lines']}")
        if kind in ("skill", "agent"):
            dw = description_words(text)
            if dw > BUDGETS["description_words"]:
                violations.append(f"{rel}: description {dw} words > {BUDGETS['description_words']}")

        if kind != "other_md":
            for line in text.splitlines():
                s = line.strip().lower()
                if len(s) > 30 and s.startswith(("- ", "* ")):
                    line_index[s].append(rel)

        if kind in ("root_md", "nested_md", "rule") and not os.path.islink(os.path.join(ROOT, rel)):
            for i, line in enumerate(text.splitlines(), 1):
                if VOLATILE_PATTERN.search(line):
                    violations.append(f"{rel}:{i}: volatile content in cached prefix -> {line.strip()[:70]}")

        if kind in ("agent", "skill", "rule", "root_md", "nested_md", "deep_dive", "other_md"):
            for i, s in multi_sentence_lines(text):
                violations.append(f"{rel}:{i}: md-format one-sentence-per-line -> {s}")

        base = os.path.dirname(os.path.join(ROOT, rel))
        for ref in set(REF_PATTERN.findall(text)):
            if ref.startswith("thoughts/"):
                continue
            if not (os.path.exists(os.path.join(ROOT, ref)) or os.path.exists(os.path.join(base, ref))):
                violations.append(f"{rel}: dead reference -> {ref}")

    for line, where in line_index.items():
        if len(set(where)) > 1:
            violations.append(f"duplicate rule in {sorted(set(where))}: {line[:60]}...")

    total = sum(
        tokens(t) for rel, (k, t) in files.items()
        if k in ("root_md", "nested_md", "rule") and not os.path.islink(os.path.join(ROOT, rel))
    )
    print(f"\nalways-loaded layer total: ~{total} tokens")

    agents_chain = sum(
        len(t.encode("utf-8")) for rel, (k, t) in files.items()
        if os.path.basename(rel) == "AGENTS.md" and not os.path.islink(os.path.join(ROOT, rel))
    )
    if agents_chain > 32 * 1024:
        violations.append(f"AGENTS.md chain {agents_chain} bytes > Codex 32 KiB cap (silent truncation)")

    for rel in files:
        if os.path.basename(rel) != "CLAUDE.md":
            continue
        d = os.path.dirname(rel)
        other = os.path.join(d, "AGENTS.md")
        if other in files and not (os.path.islink(os.path.join(ROOT, rel)) or os.path.islink(os.path.join(ROOT, other))):
            violations.append(f"{d or '.'}: CLAUDE.md and AGENTS.md are separate files — symlink one to the other")

    if violations:
        print("\nVIOLATIONS:")
        for v in violations:
            print(" -", v)
        return 1
    print("\nclean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
