#!/usr/bin/env python3
"""Generate agent_docs/harness-index.md from .claude/skills, .codex/skills, and
.claude/agents.

Single source of truth stays in each SKILL.md / agent file's frontmatter.
This script only derives an index so a non-Claude CLI (Codex) can discover
skills/agents without native triggering. Never edit the output by hand.

Dual-harness aware: a skill shared via .claude/skills/x/SKILL.md <-> a
.codex/skills/x/SKILL.md symlink is deduped by real path so it appears once,
not twice. Agents stay .claude-only - Codex has no Task-tool/subagent
equivalent to scan for.

Usage:
  python3 scripts/sync_harness.py           # (re)write the index
  python3 scripts/sync_harness.py --check   # exit 1 if the index is stale (CI/guardian)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIRS = [ROOT / ".claude" / "skills", ROOT / ".codex" / "skills"]
AGENTS_DIR = ROOT / ".claude" / "agents"
OUT = ROOT / "agent_docs" / "harness-index.md"

HEADER = (
    "<!-- GENERATED by scripts/sync_harness.py from .claude/skills, .codex/skills, "
    "and .claude/agents. -->\n"
    "<!-- Do not edit. Edit the source frontmatter, then run: make harness-index -->\n\n"
    "# Harness index (skills and agents)\n\n"
    "Before a task, check this table for an owner. Read the owner's file before you proceed.\n"
    "Claude Code triggers these natively; this index exists for Codex CLI and humans.\n"
)


def parse_frontmatter(text: str) -> dict:
    """Minimal YAML frontmatter parser: flat keys, plain scalars and >/| blocks."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip("\n")
    data: dict[str, str] = {}
    key = None
    folded: list[str] = []
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if m:
            if key and folded:
                data[key] = " ".join(folded).strip()
            key, value = m.group(1), m.group(2).strip()
            folded = []
            if value in (">", "|", ">-", "|-"):
                continue  # block scalar: collect indented lines
            data[key] = value
            key = None
        elif key is not None and (line.startswith(" ") or line == ""):
            folded.append(line.strip())
    if key and folded:
        data[key] = " ".join(folded).strip()
    return data


def clean(s: str) -> str:
    """Make a description safe for a one-line markdown table cell."""
    return re.sub(r"\s+", " ", s).replace("|", "\\|").strip()


def find_skill_files() -> list[Path]:
    """Skills across both CLIs' directories, deduped by real path so a skill
    shared via a .claude/.codex symlink pair is listed once."""
    seen_real = set()
    result = []
    for skills_dir in SKILLS_DIRS:
        if not skills_dir.is_dir():
            continue
        for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
            real = skill_md.resolve()
            if real in seen_real:
                continue
            seen_real.add(real)
            result.append(skill_md)
    return sorted(result, key=lambda p: p.parent.name)


def collect() -> str:
    rows_skills, rows_agents = [], []

    for skill_md in find_skill_files():
        fm = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = fm.get("name", skill_md.parent.name)
        desc = clean(fm.get("description", "(no description)"))
        rel = skill_md.relative_to(ROOT)
        rows_skills.append(f"| `{name}` | {desc} | `{rel}` |")

    if AGENTS_DIR.is_dir():
        for agent_md in sorted(AGENTS_DIR.glob("*.md")):
            fm = parse_frontmatter(agent_md.read_text(encoding="utf-8"))
            name = fm.get("name", agent_md.stem)
            desc = clean(fm.get("description", "(no description)"))
            model = fm.get("model", "")
            model_note = f" *(model: {model})*" if model else ""
            rel = agent_md.relative_to(ROOT)
            rows_agents.append(f"| `{name}` | {desc}{model_note} | `{rel}` |")

    parts = [HEADER]
    parts.append("\n## Skills\n\n| Skill | When to use | File |\n|---|---|---|")
    parts.extend(rows_skills or ["| — | no skills found | — |"])
    parts.append(
        "\n## Agents\n\n"
        "Claude Code: dispatch via the Task tool. Codex CLI: read the file and follow it, "
        "or run it isolated via `codex exec` (see AGENTS.md, CLI adapter notes).\n\n"
        "| Agent | Purpose | File |\n|---|---|---|"
    )
    parts.extend(rows_agents or ["| — | no agents found | — |"])
    return "\n".join(parts) + "\n"


def main() -> int:
    content = collect()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print(f"STALE: {OUT.relative_to(ROOT)} does not match frontmatter sources. "
                  f"Run: make harness-index", file=sys.stderr)
            return 1
        print("harness-index: up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    if OUT.exists() and OUT.read_text(encoding="utf-8") == content:
        print("harness-index: unchanged")  # no write -> no mtime churn, cache-friendly
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"harness-index: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
